#!/usr/bin/env bun
// tracer-digest-parity.ts — AC3 PARITY GATE.
//
// Reads the shared ground-truth fixture generated by
// `cargo test -p sa-tracer digest_reference`
// (crates/sa-tracer/tests/fixtures/digest_vectors.json), recomputes each
// auth-digest in TypeScript via api/src/auth-digest.ts (which uses the REAL
// @stellar/stellar-sdk XDR ScVal types), and asserts BYTE EQUALITY against the
// Rust reference hex for EVERY vector.
//
// Exits non-zero on ANY mismatch and prints which vector + a hex diff. This is
// the proof that the off-chain TS computation is byte-identical to the on-chain
// Rust/soroban-sdk computation.

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  computeAuthDigest,
  encodeContextRuleIdsXdr,
  fromHex,
  toHex,
} from "../src/auth-digest";

interface FixtureVector {
  label: string;
  signature_payload_hex: string;
  context_rule_ids: number[];
  context_rule_ids_xdr_hex: string;
  reference_digest_hex: string;
}

interface Fixture {
  spec: string;
  source: string;
  vectors: FixtureVector[];
}

const __dirname = dirname(fileURLToPath(import.meta.url));

// The fixture is the single source of truth, produced by the Rust reference. We
// locate it relative to this script: api/scripts -> repo root -> crates/...
const FIXTURE_PATH = resolve(
  __dirname,
  "../../crates/sa-tracer/tests/fixtures/digest_vectors.json",
);

function loadFixture(): Fixture {
  let raw: string;
  try {
    raw = readFileSync(FIXTURE_PATH, "utf8");
  } catch (e) {
    console.error(
      `\nFATAL: could not read the shared ground-truth fixture:\n  ${FIXTURE_PATH}\n` +
        `Generate it first with:\n  cargo test -p sa-tracer digest_reference\n`,
    );
    throw e;
  }
  const fixture = JSON.parse(raw) as Fixture;
  if (!Array.isArray(fixture.vectors) || fixture.vectors.length === 0) {
    throw new Error("fixture has no vectors");
  }
  return fixture;
}

function main(): void {
  const fixture = loadFixture();
  const vectors = fixture.vectors;

  console.log("auth-digest parity (AC3): TS replica vs Rust/soroban ground truth");
  console.log(`  fixture: ${FIXTURE_PATH}`);
  console.log(`  spec:    ${fixture.spec}`);
  console.log(`  source:  ${fixture.source}`);
  console.log(`  vectors: ${vectors.length}\n`);

  // Enforce the adversarial coverage the plan requires — fail loud if the
  // fixture was regenerated without the required cases.
  const idLists = vectors.map((v) => v.context_rule_ids);
  const assertCoverage = (ok: boolean, msg: string) => {
    if (!ok) {
      console.error(`COVERAGE FAILURE: ${msg}`);
      process.exit(1);
    }
  };
  assertCoverage(vectors.length >= 5, "need >= 5 adversarial vectors");
  assertCoverage(idLists.some((l) => l.length === 0), "missing empty-ids vector");
  assertCoverage(idLists.some((l) => l.length === 1), "missing single-element vector");
  assertCoverage(idLists.some((l) => l.length >= 15), "missing large (>=15) vector");
  assertCoverage(
    idLists.some((l) => l.includes(4294967295)),
    "missing u32::MAX (4294967295) boundary value",
  );
  assertCoverage(
    idLists.some((l) => l.includes(0)),
    "missing 0 boundary value",
  );

  let failures = 0;

  for (const v of vectors) {
    const signaturePayload = fromHex(v.signature_payload_hex);

    // First, an INNER parity check on the load-bearing piece: the ScVal XDR of
    // context_rule_ids must match the bytes the Rust ToXdr emitted. This isolates
    // an encoding drift from a hashing drift in the diagnostics.
    const idsXdr = encodeContextRuleIdsXdr(v.context_rule_ids);
    const idsXdrHex = toHex(idsXdr);
    if (idsXdrHex !== v.context_rule_ids_xdr_hex) {
      failures++;
      console.error(`MISMATCH [${v.label}] context_rule_ids ScVal XDR differs:`);
      console.error(`  rust : ${v.context_rule_ids_xdr_hex}`);
      console.error(`  ts   : ${idsXdrHex}`);
      console.error(`  ids  : [${v.context_rule_ids.join(", ")}]`);
      continue; // digest will also differ; the root cause is the encoding
    }

    // Then the full digest parity.
    const digest = computeAuthDigest(signaturePayload, v.context_rule_ids);
    const digestHex = toHex(digest);

    if (digestHex !== v.reference_digest_hex) {
      failures++;
      console.error(`MISMATCH [${v.label}] auth-digest differs:`);
      console.error(`  rust : ${v.reference_digest_hex}`);
      console.error(`  ts   : ${digestHex}`);
      console.error(`  payload: ${v.signature_payload_hex}`);
      console.error(`  ids    : [${v.context_rule_ids.join(", ")}]`);
      console.error(`  idsXdr : ${idsXdrHex}`);
    } else {
      console.log(
        `  OK [${v.label.padEnd(16)}] ids=${String(v.context_rule_ids.length).padStart(2)} ` +
          `digest=${digestHex}`,
      );
    }
  }

  if (failures > 0) {
    console.error(`\nPARITY FAILED: ${failures}/${vectors.length} vector(s) mismatch.`);
    process.exit(1);
  }

  console.log(
    `\nPARITY OK: all ${vectors.length} vectors byte-identical to the Rust/soroban ground truth.`,
  );
}

main();
