//! Strategy adapter trait for Baku vaults.
//!
//! A `Strategy` is any Soroban contract that knows how to deposit a single
//! underlying asset into some yield source (lending pool, AMM LP, etc.) and
//! report current value. The vault calls strategies through the typed
//! `StrategyClient` generated by the `#[contractclient]` macro — registering a
//! contract that does not implement this shape fails fast at the SDK boundary
//! instead of mid-transaction.
//!
//! Auth model: every state-changing method calls `vault.require_auth()` inside
//! the strategy implementation. The vault is the only authorized caller.
//! Users never call the strategy directly.
//!
//! Pre-existing decision tracking:
//! - D2: typed dispatch via `#[contractclient(name = "StrategyClient")]`
//! - D4 + D10: vault enforces `min_amount_out` on withdraw; strategy returns
//!   the amount it actually delivered so the vault can verify the floor.
//! - D5: errors are typed via `StrategyError` (see `errors` module).

#![no_std]

use soroban_sdk::{contractclient, Address, Env};

pub mod errors;
pub use errors::StrategyError;

/// Adapter interface for any yield source.
///
/// All `Result` returns convert to typed Soroban errors at the contract boundary.
/// Implementations MUST call `vault.require_auth()` at the top of each
/// state-changing method.
#[contractclient(name = "StrategyClient")]
pub trait StrategyInterface {
    /// Deposit `amount` of the underlying asset into the strategy on behalf of
    /// `vault`. The strategy assumes the vault has already transferred the
    /// underlying tokens to the strategy contract address before calling.
    fn deposit(env: Env, vault: Address, amount: i128) -> Result<(), StrategyError>;

    /// Withdraw up to `amount` of the underlying back to `vault`. Returns the
    /// amount actually delivered (may be less than requested due to swap-back
    /// slippage for LP strategies). The vault enforces a `min_amount_out`
    /// floor on top of this return value.
    fn withdraw(env: Env, vault: Address, amount: i128) -> Result<i128, StrategyError>;

    /// View. Returns the amount the user would receive on a FULL exit at this
    /// instant, including swap-back slippage / pool reserve math for LP
    /// strategies. This is the source of truth for `vault.total_assets()` and
    /// price-per-share calculations.
    ///
    /// NOTE: for LP-based strategies this is an ESTIMATE — pool reserves shift
    /// between this read and the actual withdraw. The vault uses this to
    /// preview redemption; the `min_amount_out` parameter on withdraw is the
    /// on-chain safety floor.
    fn current_value(env: Env) -> i128;

    /// Compound rewards into the position. For Blend lending this is a no-op
    /// when interest auto-compounds in the reserve; it may claim BLND rewards
    /// when emitted. Returns the amount harvested (0 if no-op).
    ///
    /// Permissioned to vault auth in V0; mainnet would consider permissionless.
    fn harvest(env: Env, vault: Address) -> Result<i128, StrategyError>;

    /// Read the strategy's current annualized yield estimate in basis points
    /// (1% = 100). V0 stores this as an admin-set scalar because pool APY
    /// cannot be reliably computed on-chain for all strategy types (Soroswap
    /// APY needs off-chain volume history). The API reads this value directly
    /// and surfaces it to the wallet.
    fn pool_apy(env: Env) -> u32;

    /// Admin-only setter for the pool APY estimate. The admin is the strategy
    /// contract's own admin (set at instantiation), NOT the vault.
    fn set_pool_apy_bps(env: Env, admin: Address, bps: u32) -> Result<(), StrategyError>;
}

/// Recompute the standard preview-redeem amount: `(shares * total_assets) / total_supply`.
///
/// Used by both the vault (for share math) and tests. Kept here so all
/// strategy/vault code uses the same formula.
pub fn preview_redeem(shares: i128, total_assets: i128, total_supply: i128) -> i128 {
    if total_supply == 0 {
        return 0;
    }
    // No need for ceiling math on withdraw — round down protects the vault.
    shares.saturating_mul(total_assets) / total_supply
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preview_redeem_basic() {
        // 100 shares out of 1000 total, against 5000 assets => 500
        assert_eq!(preview_redeem(100, 5000, 1000), 500);
    }

    #[test]
    fn preview_redeem_zero_supply_returns_zero() {
        assert_eq!(preview_redeem(100, 5000, 0), 0);
    }

    #[test]
    fn preview_redeem_zero_shares_returns_zero() {
        assert_eq!(preview_redeem(0, 5000, 1000), 0);
    }

    #[test]
    fn preview_redeem_rounds_down() {
        // 1 share of 3 total against 10 assets => 10/3 = 3 (round down, vault keeps the 1)
        assert_eq!(preview_redeem(1, 10, 3), 3);
    }
}
