// auth-digest.ts — off-chain TypeScript replica of the Smart Account auth-digest.
//
// PROVES AC3: this computation MUST be byte-identical to the on-chain
// Rust/soroban-sdk computation. The ground truth is generated by
// `cargo test -p sa-tracer digest_reference` (crates/sa-tracer). Parity is
// asserted by `bun run tracer:digest-parity` (scripts/tracer-digest-parity.ts)
// against the shared fixture crates/sa-tracer/tests/fixtures/digest_vectors.json.
//
// ## auth-digest spec (validated by the P1 tracer against stellar-accounts 0.7.1,
// smart_account/storage.rs:492-495 — GROUND TRUTH; honor it exactly):
//
//   auth_digest = SHA-256( raw32(signature_payload) || ScValXdr(context_rule_ids) )
//
//   - signature_payload contributes its 32 RAW bytes (Hash<32>::to_bytes()),
//     NOT the XDR of the hash.
//   - context_rule_ids is a Vec<u32> serialized as the FULL soroban ScVal XDR of
//     the host vec (SCV_VEC discriminant + Option<ScVec> present-flag + length +
//     per-element SCV_U32 discriminant + value), produced here via the REAL
//     @stellar/stellar-sdk XDR ScVal types. A hand-rolled byte array is FORBIDDEN
//     — using the SDK's xdr.ScVal.scvVec([xdr.ScVal.scvU32(n), ...]).toXDR() is
//     the load-bearing parity guarantee.

import { hash, xdr } from "@stellar/stellar-sdk";

/**
 * Encode a list of context rule ids as the soroban ScVal XDR of a host Vec<u32>.
 *
 * This uses the REAL stellar-sdk XDR ScVal types — `xdr.ScVal.scvVec` of
 * `xdr.ScVal.scvU32` — so the emitted bytes are exactly the SCV_VEC +
 * per-element SCV_U32 framing that soroban-sdk's `ToXdr` produces on-chain.
 * It is NOT a hand-assembled byte buffer.
 *
 * For [0,1,42] this yields 36 bytes; for [] it yields 12 bytes; general form is
 * 12 + 8*N bytes.
 *
 * @param contextRuleIds non-negative u32 rule ids (0 .. 4294967295)
 */
export function encodeContextRuleIdsXdr(contextRuleIds: number[]): Uint8Array {
  const elements = contextRuleIds.map((id) => {
    if (!Number.isInteger(id) || id < 0 || id > 0xffff_ffff) {
      throw new Error(
        `context_rule_id out of u32 range: ${id} (must be an integer in [0, 4294967295])`,
      );
    }
    // scvU32 takes a u32; the SDK accepts a JS number for values <= 2^32-1.
    return xdr.ScVal.scvU32(id);
  });

  // xdr.ScVal.scvVec(...) builds SCV_VEC( Some(ScVec[...]) ). .toXDR() emits the
  // canonical soroban ScVal XDR: SCV_VEC discriminant + present-flag + length +
  // each element's full ScVal XDR (SCV_U32 discriminant + value).
  const scval = xdr.ScVal.scvVec(elements);
  const buf = scval.toXDR(); // Buffer (Node/Bun) — a Uint8Array subclass
  return Uint8Array.from(buf);
}

/**
 * Compute the Smart Account auth-digest off-chain.
 *
 *   auth_digest = SHA-256( signaturePayload (32 raw bytes) || ScValXdr(contextRuleIds) )
 *
 * @param signaturePayload the 32 RAW bytes of the host signature payload
 *   (Hash<32>::to_bytes()). MUST be exactly 32 bytes.
 * @param contextRuleIds   the Vec<u32> of context rule ids.
 * @returns the 32-byte SHA-256 auth-digest.
 */
export function computeAuthDigest(
  signaturePayload: Uint8Array,
  contextRuleIds: number[],
): Uint8Array {
  if (signaturePayload.length !== 32) {
    throw new Error(
      `signature_payload must be 32 raw bytes, got ${signaturePayload.length}`,
    );
  }

  const idsXdr = encodeContextRuleIdsXdr(contextRuleIds);

  // preimage = raw32(signature_payload) || ScValXdr(context_rule_ids)
  const preimage = new Uint8Array(signaturePayload.length + idsXdr.length);
  preimage.set(signaturePayload, 0);
  preimage.set(idsXdr, signaturePayload.length);

  // SHA-256 via the stellar-sdk `hash` helper (the same digest soroban's
  // crypto().sha256 computes).
  const digest = hash(Buffer.from(preimage));
  return Uint8Array.from(digest);
}

/** Lowercase hex of a byte array. */
export function toHex(bytes: Uint8Array): string {
  let s = "";
  for (const b of bytes) {
    s += b.toString(16).padStart(2, "0");
  }
  return s;
}

/** Parse a lowercase/uppercase hex string into bytes. */
export function fromHex(hexStr: string): Uint8Array {
  if (hexStr.length % 2 !== 0) {
    throw new Error(`hex string has odd length: ${hexStr.length}`);
  }
  const out = new Uint8Array(hexStr.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = Number.parseInt(hexStr.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}
